param([string]$Root = $PSScriptRoot)

$ErrorActionPreference = 'Continue'
Set-Location -LiteralPath $Root
$logPath = Join-Path $Root 'watch-sync.log'
$heartbeatPath = Join-Path $Root 'watch-sync.heartbeat'
$watchPaths = @($Root)
$watchers = foreach ($path in $watchPaths) {
  $w = [System.IO.FileSystemWatcher]::new($path)
  $w.IncludeSubdirectories = $true
  $w.NotifyFilter = [System.IO.NotifyFilters]'FileName, DirectoryName, LastWrite, Size'
  $w.EnableRaisingEvents = $true
  foreach ($name in 'Changed','Created','Deleted','Renamed') { Register-ObjectEvent -InputObject $w -EventName $name | Out-Null }
  $w
}

function Invoke-Publish {
  $started = Get-Date
  "[$started] Checking local Ryhze changes" | Add-Content -LiteralPath $logPath
  & (Join-Path $Root 'sync-library.ps1') -Root $Root | Out-Null
  git add -A
  git diff --cached --quiet
  if ($LASTEXITCODE -ne 0) {
    git commit -m 'Auto-sync Ryhze updates' | Out-Null
    if ($LASTEXITCODE -eq 0) {
      git push origin main 2>&1 | Out-Null
      if ($LASTEXITCODE -ne 0) {
        # Another device may have published first. Rebase and retry without losing this PC's change.
        git pull --rebase origin main 2>&1 | Out-Null
        if ($LASTEXITCODE -eq 0) { git push origin main 2>&1 | Out-Null }
      }
      if ($LASTEXITCODE -eq 0) { "[$(Get-Date)] Published successfully" | Add-Content -LiteralPath $logPath }
      else { "[$(Get-Date)] Publish failed; will retry after the next file change" | Add-Content -LiteralPath $logPath }
    }
  }
  if ($env:R2_ACCESS_KEY_ID -and $env:R2_SECRET_ACCESS_KEY) {
    node (Join-Path $Root 'sync-r2-s3.mjs') | Out-Null
  }
}

# Reconcile once on launch, so changes made while the PC or watcher was stopped are published too.
$lastLocal = Get-Date
$lastRemoteCheck = [datetime]::MinValue
$busy = $false
while ($true) {
  $event = Wait-Event -Timeout 2
  if ($event) {
    $path = $event.SourceEventArgs.FullPath
    Remove-Event -EventIdentifier $event.EventIdentifier -ErrorAction SilentlyContinue
    # library-data.js and this log are generated by this watcher; they must not queue another publish.
    if ($path -notmatch '[\\/]\.git([\\/]|$)' -and $path -notmatch 'mobile-conversion.*\.log$' -and $path -notmatch '[\\/]library-data\.js$' -and $path -notmatch '[\\/]watch-sync\.(log|heartbeat)$') { $lastLocal = Get-Date }
  }

  if (((Get-Date) - (if (Test-Path -LiteralPath $heartbeatPath) { (Get-Item -LiteralPath $heartbeatPath).LastWriteTime } else { [datetime]::MinValue })).TotalSeconds -ge 20) {
    Set-Content -LiteralPath $heartbeatPath -Value (Get-Date).ToString('o') -Encoding ascii
  }

  if (-not $busy -and $lastLocal -ne [datetime]::MinValue -and ((Get-Date) - $lastLocal).TotalSeconds -ge 2) {
    $busy = $true; $lastLocal = [datetime]::MinValue
    Invoke-Publish
    $busy = $false
  }

  if (-not $busy -and ((Get-Date) - $lastRemoteCheck).TotalSeconds -ge 30) {
    $lastRemoteCheck = Get-Date
    git fetch origin main | Out-Null
    $head = git rev-parse HEAD 2>$null
    $remote = git rev-parse origin/main 2>$null
    if ($head -and $remote -and $head -ne $remote) {
      $dirty = git status --porcelain
      if (-not $dirty) {
        $busy = $true
        git pull --ff-only origin main | Out-Null
        Invoke-Publish
        $busy = $false
      }
    }
  }
}
